## Transforming Data

In [2]:
import pandas as pd

pokemon_info = pd.read_json("../data-files/pokemon_info_generation_1.json")
pokemon_info2 = pd.read_json("../data-files/pokemon_description_generation_1.json")

1. Investigate the Data. Check if there is errors, duplicated, etc.

In [3]:
def show_section(title, content):
    print(f"{title}:")
    content()
    print()

sections = [
    ("Shape", lambda: print(pokemon_info.shape)),
    ("DataFrame info", pokemon_info.info),
    ("First five rows", lambda: display(pokemon_info.head())),
    ("Data types", lambda: print(pokemon_info.dtypes)),
    ("Missing values", lambda: print(pokemon_info.isna().sum())),
    ("Duplicate rows", lambda: print(pokemon_info.duplicated().sum())),
    ("Check Impossible Values", lambda: print(pokemon_info.describe()))
]

print("File 1 Infos:")
for title, content in sections:
    show_section(title, content)

File 1 Infos:
Shape:
(151, 4)

DataFrame info:
<class 'pandas.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         151 non-null    int64
 1   Name       151 non-null    str
 2   Type       151 non-null    str
 3   Abilities  151 non-null    str
dtypes: int64(1), str(3)
memory usage: 4.8 KB

First five rows:

   ID        Name           Type              Abilities
0   1   Bulbasaur  grass, poison  overgrow, chlorophyll
1   2     Ivysaur  grass, poison  overgrow, chlorophyll
2   3    Venusaur  grass, poison  overgrow, chlorophyll
3   4  Charmander           fire     blaze, solar-power
4   5  Charmeleon           fire     blaze, solar-power

Data types:
ID           int64
Name           str
Type           str
Abilities      str
dtype: object

Missing values:
ID           0
Name         0
Type         0
Abilities    0
dtype: int64

Duplicate rows:
0

Check Impossible Values:
               ID
count  151.000000
mean    76.000000
std     43.734045
min      1.000000
25%     38.500000
50%     76.000000
75%    113.500000
max    151.000000

In [ ]:
def show_section(title, content):
    """Print a section title, execute its content, and add a blank line."""
    print(f"{title}:")
    content()
    print()

sections = [
    ("Shape", lambda: print(pokemon_info2.shape)),
    ("DataFrame info", pokemon_info2.info),
    ("First five rows", lambda: display(pokemon_info2.head())),
    ("Data types", lambda: print(pokemon_info2.dtypes)),
    ("Missing values", lambda: print(pokemon_info2.isna().sum())),
    ("Duplicate rows", lambda: print(pokemon_info2.duplicated().sum())),
    ("Check Impossible Values", lambda: print(pokemon_info2.describe()))
]

print("File 2 Infos:")
for title, content in sections:
    show_section(title, content)

File 2 Infos:
Shape:
(151, 3)

DataFrame info:
<class 'pandas.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           151 non-null    int64
 1   Name         151 non-null    str
 2   Description  151 non-null    str
dtypes: int64(1), str(2)
memory usage: 3.7 KB

First five rows:

   ID        Name                                        Description
0   1   Bulbasaur  A strange seed was planted on its back at birt...
1   2     Ivysaur  When the bulb on its back grows large, it appe...
2   3    Venusaur  The plant blooms when it is absorbing solar en...
3   4  Charmander  Obviously prefers hot places. When it rains, s...
4   5  Charmeleon  When it swings its burning tail, it elevates t...

Data types:
ID             int64
Name             str
Description      str
dtype: object

Missing values:
ID             0
Name           0
Description    0
dtype: int64

Duplicate rows:
0

Check Impossible Values:
               ID
count  151.000000
mean    76.000000
std     43.734045
min      1.000000
25%     38.500000
50%     76.000000
75%    113.500000
max    151.000000

2. Transform the Data

In [5]:
rename_map = {
    "ID": "pokedex_no",
    "Name": "pokemon",
    "Description": "description",
    "Abilities": "ability",
    "Type": "type",
}

pokemon_info = (
    pokemon_info
    .merge(pokemon_info2[["ID", "Description"]], on="ID", how="left")
    .rename(columns=rename_map)
    [["pokedex_no", "pokemon", "type", "ability", "description"]]
)

display(pokemon_info.head())

,pokedex_no,pokemon,type,ability,description
0,1,Bulbasaur,"grass, poison","overgrow, chlorophyll",A strange seed was planted on its back at birt...
1,2,Ivysaur,"grass, poison","overgrow, chlorophyll","When the bulb on its back grows large, it appe..."
2,3,Venusaur,"grass, poison","overgrow, chlorophyll",The plant blooms when it is absorbing solar en...
3,4,Charmander,fire,"blaze, solar-power","Obviously prefers hot places. When it rains, s..."
4,5,Charmeleon,fire,"blaze, solar-power","When it swings its burning tail, it elevates t..."

3. Retrieve the Cleaned Data

In [6]:
pokemon_info.to_json("../data-files/cleaned_pokemon_generation_1.json", index=False)
print("Cleaned data saved successfully.")

Cleaned data saved successfully.